### ISSUE TITLE
[Improvement] Remove the blank list element 

### ISSUE THREAD

**Issue by iatharva** [saurodip1708/saurodip1708.github.io#1]
There is `li` element present in the `about me` section which is blank, you can remove that.

**Comment by saurodip1708** [comment]
Thank you for your response

**Comment by saurodip1708** [comment]
There is one pic but due to some issue it's not working

**Comment by iatharva** [comment]
There is still one problem of google map not loading

**Comment by iatharva** [comment]
Please check another issue too and you can close it if it's solved

**Comment by saurodip1708** [comment]
I will solve it today there is problem in api requesting

**Comment by saurodip1708** [comment]
Which blank list?

**Comment by iatharva** [comment]
Not the blank list one, check the issues section

**Comment by saurodip1708** [comment]
Which one

**Comment by iatharva** [comment]
Never mind, I closed it as it was already solved. I was referring to [this](https://github.com/saurodip1708/saurodip1708.github.io/issues/2#)

**Comment by saurodip1708** [comment]
Ok, thanks.

**Comment by saurodip1708** [comment]
Now check the website Google map is also working fine
By 2-3 days form will also work

**Comment by iatharva** [comment]
Looks good!

**Comment by saurodip1708** [comment]
Glad you like it!
